"""Snapshot and restore for a target's data directory.

Mechanic snapshots a target's data directory (OpenClaw's config dir, Hermes's
home) before every nightly update so a verify failure can be rolled back.
Snapshots are tar.gz archives, not raw directory copies: both products are
live daemons that write continuously to their directories, and a
copytree-based snapshot races against those writes (see the v0.1 install
postmortem in SESSIONS.md 2026-05-23).

Every target has its own SnapshotStore. OpenClaw keeps the original layout
directly under snapshots/ so existing installs need no migration; other
targets live under snapshots/<target>/.

Disk layout (CLAUDE.md section 5), shown for OpenClaw:

    ~/Library/Application Support/tekrescue-mechanic/snapshots/
    |-- first-known-good/    pristine pre-Mechanic anchor, never auto-pruned
    |   |-- metadata.json
    |   `-- archive.tar.gz
    |-- last-known-good/     latest verified-working state, never auto-pruned
    |   |-- metadata.json
    |   `-- archive.tar.gz
    `-- nightly/
        `-- <YYYY-MM-DDTHH-MM-SSZ>/   rolling, pruned by SNAPSHOT_RETENTION_DAYS
            |-- metadata.json
            `-- archive.tar.gz

`tmp/` and `logs/` inside OpenClaw's config dir are excluded from snapshots:
they're high-churn caches with no recovery value, and they're the source of
the live-daemon race that broke v0.1's first install attempt. Hermes's
excludes mirror its own `hermes backup` list (the code checkout, package
manager stores, caches, prior backups, browser profiles, and its own
state-snapshots, each of which holds a full copy of state.db).

SQLite databases get special treatment where a store declares them
(`sqlite_globs`): a raw tar of a live WAL-mode database can be
inconsistent, so capture copies each one with SQLite's online backup API
(Python's sqlite3 module, no external tool) into `<snapshot>/sqlite/`,
gzip-compressed, and leaves the live `.db`, `-wal`, `-shm` files out of
the tar. Restore untars, then puts the copies back and drops stale
sidecars. On the maintainer's Mac mini state.db is 638 MB; this is the
difference between a snapshot and a disk full.

Restore is operator-driven (via `mechanic restore`). It stops the target's
daemon, untars over the data dir, and restarts the daemon. The nightly
updater never auto-restores; on verify failure it logs and notifies, and
the operator decides whether to roll back.
"""

from __future__ import annotations

import gzip
import json
import logging
import shutil
import sqlite3
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .config import Config, SNAPSHOT_DIR, clean_subprocess_env


KIND_FIRST_KNOWN_GOOD = "first-known-good"
KIND_LAST_KNOWN_GOOD = "last-known-good"
KIND_NIGHTLY = "nightly"
VALID_KINDS = (KIND_FIRST_KNOWN_GOOD, KIND_LAST_KNOWN_GOOD, KIND_NIGHTLY)

NIGHTLY_DIR = SNAPSHOT_DIR / "nightly"
FIRST_KNOWN_GOOD_DIR = SNAPSHOT_DIR / KIND_FIRST_KNOWN_GOOD
LAST_KNOWN_GOOD_DIR = SNAPSHOT_DIR / KIND_LAST_KNOWN_GOOD

ARCHIVE_FILENAME = "archive.tar.gz"
METADATA_FILENAME = "metadata.json"

# Subdirectories of OPENCLAW_CONFIG_PATH that are excluded from snapshots.
# These are high-churn caches that race against the live daemon and have no
# recovery value.
DEFAULT_EXCLUDES = ("tmp", "logs")

# Top-level entries of HERMES_HOME left out of Mechanic's archive. Mirrors
# what `hermes backup` skips: the code checkout (git has it), the package
# manager's tool store and interpreter generations (regenerated by
# `hermes pm install`), caches, prior backups, and browser profiles that
# hold cookies. `state-snapshots/` is kept on purpose: `hermes backup
# --quick`, which Mechanic runs first, lands a SQLite-safe copy of state.db
# there, so the archive carries a consistent database as well as the live
# one.
HERMES_EXCLUDES = (
    "hermes-agent", "installs", "tools", "cache", ".cache", "backups", "logs",
    "state-snapshots", "browser_profiles", "browser-profiles", "browser-profile",
    "checkpoints", "node_modules", ".venv", "venv",
)
# Patterns excluded at any depth (bsdtar and GNU tar both match these
# against the path tail).
HERMES_EXCLUDE_PATTERNS = ("*/__pycache__", "*/node_modules", "*/.venv")
# SQLite databases captured with the online backup API instead of tar.
HERMES_SQLITE_GLOBS = ("*.db", "cron/*.db")
SQLITE_SIDECAR_SUFFIXES = ("-wal", "-shm", "-journal")
SQLITE_DIRNAME = "sqlite"

_TAR_TIMEOUT_SECONDS = 600

_LOG = logging.getLogger(__name__)


class RollbackError(Exception):
    """Raised when a snapshot or restore operation fails."""


class InsufficientDiskError(RollbackError):
    """Raised when free disk is below MIN_FREE_DISK_MB_FOR_SNAPSHOT."""


@dataclass(frozen=True)
class SnapshotStore:
    """Where one target's snapshots live and what they contain.

    `root` holds first-known-good/, last-known-good/ and nightly/. `source`
    is the directory archived. `excludes` are top-level entries of `source`
    to skip; `exclude_patterns` are tar patterns matched at any depth.
    """

    name: str
    root: Path
    source: Path
    excludes: tuple[str, ...] = ()
    exclude_patterns: tuple[str, ...] = ()
    #: Globs (relative to `source`) of SQLite databases to copy with the
    #: online backup API rather than tar. Their live files and sidecars are
    #: excluded from the archive.
    sqlite_globs: tuple[str, ...] = ()

    @property
    def nightly_dir(self) -> Path:
        return self.root / "nightly"

    @property
    def first_known_good_dir(self) -> Path:
        return self.root / KIND_FIRST_KNOWN_GOOD

    @property
    def last_known_good_dir(self) -> Path:
        return self.root / KIND_LAST_KNOWN_GOOD


def openclaw_store(config: Config) -> SnapshotStore:
    """OpenClaw's store: the original v0.1 layout directly under snapshots/."""
    return SnapshotStore(
        name="openclaw",
        root=SNAPSHOT_DIR,
        source=config.openclaw_config_path,
        excludes=DEFAULT_EXCLUDES,
    )


def hermes_store(config: Config) -> SnapshotStore:
    """Hermes's store, under snapshots/hermes/, archiving HERMES_HOME."""
    if config.hermes is None:
        raise RollbackError("hermes is not in TARGETS")
    return SnapshotStore(
        name="hermes",
        root=SNAPSHOT_DIR / "hermes",
        source=config.hermes.home,
        excludes=HERMES_EXCLUDES,
        exclude_patterns=HERMES_EXCLUDE_PATTERNS,
        sqlite_globs=HERMES_SQLITE_GLOBS,
    )


def store_for(config: Config, target: str) -> SnapshotStore:
    """The SnapshotStore for a target name."""
    if target == "openclaw":
        return openclaw_store(config)
    if target == "hermes":
        return hermes_store(config)
    raise RollbackError(f"unknown target {target!r}")


@dataclass(frozen=True)
class Snapshot:
    """Pointer to a snapshot directory plus its parsed metadata.

    `extra` carries target-specific facts (for Hermes, the git commit the
    checkout was on, so a restore can put the code back too).
    """

    path: Path
    snapshot_id: str
    kind: str
    captured_at: str
    version: Optional[str]
    source: str
    verified_healthy: bool
    extra: dict = field(default_factory=dict)

    @property
    def archive_path(self) -> Path:
        """Path to the tar.gz archive inside this snapshot."""
        return self.path / ARCHIVE_FILENAME

    @property
    def openclaw_version(self) -> Optional[str]:
        """Pre-v0.2 name for `version`, kept for callers and docs."""
        return self.version


def free_disk_mb(path: Path) -> int:
    """Return the free space (in megabytes) on the filesystem holding `path`.

    If the path does not exist yet, walks up to its first existing parent so
    install-time callers can probe before SNAPSHOT_DIR is created.
    """
    probe = path
    while not probe.exists():
        if probe.parent == probe:
            break
        probe = probe.parent
    usage = shutil.disk_usage(probe)
    return usage.free // (1024 * 1024)


# Emergency pruning never removes the newest N nightlies, no matter how
# short on disk we are. Recent restore points outrank a completed run.
EMERGENCY_PRUNE_MIN_KEEP = 3


def _archive_mb_from_metadata(snapshot_dir: Path) -> int:
    """Read archive_size_bytes from a snapshot's metadata.json, in MB.

    Returns 0 when the metadata is missing or unreadable so callers can
    fall back to the configured floor.
    """
    meta_path = snapshot_dir / METADATA_FILENAME
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        return int(meta.get("archive_size_bytes", 0)) // (1024 * 1024)
    except (OSError, ValueError, TypeError):
        return 0


def _estimate_next_archive_mb(store: SnapshotStore) -> int:
    """Best guess at the next archive's size, in MB.

    Prefers last-known-good's recorded size (refreshed after every
    successful run), falls back to the newest nightly, else 0.
    """
    if store.last_known_good_dir.is_dir():
        mb = _archive_mb_from_metadata(store.last_known_good_dir)
        if mb:
            return mb
    newest = latest_nightly(store)
    if newest is not None:
        return _archive_mb_from_metadata(newest.path)
    return 0


def ensure_disk_headroom(store: SnapshotStore, *, min_free_mb: int) -> list[str]:
    """Pre-flight disk check with emergency pruning of the oldest nightlies.

    A run's peak transient need is roughly TWO archives: the nightly
    snapshot itself, plus the last-known-good rewrite after a successful
    verify (which tars into a tmp sibling before the old copy is removed).
    We require that much free space (with a 10 percent growth margin, and
    never less than MIN_FREE_DISK_MB_FOR_SNAPSHOT), and if the volume is
    short we delete the OLDEST nightly snapshots one at a time until the
    run fits. Sticky snapshots (first-known-good, last-known-good) are
    never touched, and the newest EMERGENCY_PRUNE_MIN_KEEP nightlies
    always survive.

    Returns the list of pruned snapshot ids, empty when nothing was
    pruned. Raises InsufficientDiskError if space is still short after
    pruning. Per CLAUDE.md section 5: we never proceed with an update if
    a rollback would not be possible.
    """
    store.root.mkdir(parents=True, exist_ok=True)
    est_mb = _estimate_next_archive_mb(store)
    required = max(min_free_mb, (est_mb * 2 * 11) // 10)
    pruned: list[str] = []
    while free_disk_mb(store.root) < required:
        if not store.nightly_dir.exists():
            break
        victims = sorted(
            (
                p
                for p in store.nightly_dir.iterdir()
                if p.is_dir() and not p.name.startswith(".")
            ),
            key=lambda p: p.name,
        )
        if len(victims) <= EMERGENCY_PRUNE_MIN_KEEP:
            break
        victim = victims[0]
        try:
            shutil.rmtree(victim)
        except OSError as exc:
            _LOG.warning("emergency prune could not remove %s: %s", victim, exc)
            break
        pruned.append(victim.name)
        _LOG.warning(
            "emergency-pruned oldest nightly snapshot %s to free disk "
            "(free now %d MB, run needs %d MB)",
            victim.name,
            free_disk_mb(store.root),
            required,
        )
    free_mb = free_disk_mb(store.root)
    if free_mb < required:
        after = (
            f" even after emergency-pruning {len(pruned)} old snapshot(s)"
            if pruned
            else ""
        )
        raise InsufficientDiskError(
            f"Free disk on snapshot volume is {free_mb} MB but this run needs "
            f"about {required} MB{after}. "
            f"Refusing to start an update without rollback headroom."
        )
    return pruned


def capture_snapshot(
    store: SnapshotStore,
    *,
    kind: str,
    version: Optional[str] = None,
    verified_healthy: bool = False,
    snapshot_id: Optional[str] = None,
    extra: Optional[dict] = None,
) -> Snapshot:
    """Snapshot the store's source directory as a tar.gz archive.

    Atomic on the same filesystem: tar writes into a hidden tmp sibling and
    the directory is renamed into place after metadata.json is written. For
    sticky kinds (first-known-good, last-known-good) this replaces whatever
    was there.

    Args:
        store: The target's SnapshotStore (source, excludes, layout).
        kind: One of VALID_KINDS.
        version: The target's reported version at capture time.
        verified_healthy: True if the target passed a health check at capture.
        snapshot_id: Override the auto-generated id. Only used by tests.
        extra: Target-specific facts to keep in metadata.json.

    Raises:
        RollbackError: kind invalid, source missing, or tar invocation fails.
    """
    if kind not in VALID_KINDS:
        raise RollbackError(
            f"Unknown snapshot kind {kind!r}. Must be one of {VALID_KINDS}."
        )

    source = store.source
    if not source.exists():
        raise RollbackError(
            f"{store.name} data path {source} does not exist; nothing to snapshot."
        )
    if not source.is_dir():
        raise RollbackError(
            f"{store.name} data path {source} is not a directory."
        )

    sid = snapshot_id or _generate_snapshot_id()
    destination = _destination_for(store, kind, sid)
    destination.parent.mkdir(parents=True, exist_ok=True)

    tmp_dir = destination.with_name(f".{destination.name}.tmp-{sid}")
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True)

    archive_tmp = tmp_dir / ARCHIVE_FILENAME

    try:
        databases = _snapshot_sqlite(store, tmp_dir / SQLITE_DIRNAME)
        _run_tar_create(
            source, archive_tmp,
            excludes=store.excludes,
            exclude_patterns=store.exclude_patterns + _sqlite_tar_excludes(store, databases),
        )
        metadata = {
            "snapshot_id": sid,
            "kind": kind,
            "target": store.name,
            "captured_at": _now_iso(),
            "version": version,
            "source": str(source),
            # Pre-v0.2 names, kept so older tooling and docs still read.
            "openclaw_version": version if store.name == "openclaw" else None,
            "openclaw_config_source": str(source) if store.name == "openclaw" else None,
            "verified_healthy": bool(verified_healthy),
            "archive_filename": ARCHIVE_FILENAME,
            "excludes": list(store.excludes),
            "exclude_patterns": list(store.exclude_patterns),
            "sqlite_databases": databases,
            "archive_size_bytes": archive_tmp.stat().st_size
            + sum((tmp_dir / SQLITE_DIRNAME / f"{d}.gz").stat().st_size for d in databases),
            "extra": dict(extra or {}),
        }
        (tmp_dir / METADATA_FILENAME).write_text(
            json.dumps(metadata, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        _swap_into_place(tmp_dir, destination)
    except Exception:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise

    _LOG.info(
        "captured %s %s snapshot at %s (%d MB)",
        store.name,
        kind,
        destination,
        metadata["archive_size_bytes"] // (1024 * 1024),
    )
    return _snapshot_from_path(destination)


def restore_snapshot(store: SnapshotStore, snapshot: Snapshot) -> None:
    """Replace the store's source directory with the contents of `snapshot`.

    CALLER MUST STOP THE TARGET'S DAEMON FIRST. This function does not stop
    or start the daemon; the `mechanic restore` CLI wraps the lifecycle.
    If the daemon is running while we restore, it will recreate files in
    the data dir mid-untar and the restore will be incomplete.

    Strategy: move the live data dir to a sibling `.pre-restore-*`, untar
    the archive into the original location, move the store's EXCLUDED
    top-level entries back from the sibling (they were never archived:
    OpenClaw's tmp/ and logs/, and for Hermes the code checkout and the
    package manager's stores, which a restore must not destroy), then
    remove the sibling on success (or roll the rename back on failure).
    """
    if not snapshot.archive_path.is_file():
        raise RollbackError(
            f"Snapshot at {snapshot.path} is missing {ARCHIVE_FILENAME}."
        )

    target = store.source
    target.parent.mkdir(parents=True, exist_ok=True)

    backup: Optional[Path] = None
    if target.exists():
        backup = target.with_name(
            f".{target.name}.pre-restore-{_generate_snapshot_id()}"
        )
        target.rename(backup)

    try:
        target.mkdir(parents=True, exist_ok=False)
        _run_tar_extract(snapshot.archive_path, into=target.parent, strip_to=target.name)
        if backup is not None:
            _carry_over_excluded(backup, target, store.excludes)
        _restore_sqlite(snapshot, target)
    except Exception:
        if backup is not None and not _has_meaningful_content(target):
            if target.exists():
                shutil.rmtree(target, ignore_errors=True)
            backup.rename(target)
        raise

    if backup is not None:
        shutil.rmtree(backup, ignore_errors=True)

    _LOG.info("restored %s data from %s", store.name, snapshot.path)


def prune_nightlies(store: SnapshotStore, *, keep: int) -> list[Path]:
    """Trim nightly/ to at most `keep` entries (SNAPSHOT_RETENTION_DAYS).

    Never touches first-known-good or last-known-good. Returns the list of
    paths that were removed (oldest first).
    """
    if not store.nightly_dir.exists():
        return []

    nightlies = sorted(
        (p for p in store.nightly_dir.iterdir() if p.is_dir() and not p.name.startswith(".")),
        key=lambda p: p.name,
    )
    if len(nightlies) <= keep:
        return []

    to_remove = nightlies[: len(nightlies) - keep]
    removed: list[Path] = []
    for path in to_remove:
        try:
            shutil.rmtree(path)
            removed.append(path)
            _LOG.info("pruned nightly snapshot %s", path.name)
        except OSError as exc:
            _LOG.warning("could not prune %s: %s", path, exc)
    return removed


def latest_nightly(store: SnapshotStore) -> Optional[Snapshot]:
    """Return the newest nightly snapshot, or None if there are none."""
    if not store.nightly_dir.exists():
        return None
    candidates = sorted(
        (p for p in store.nightly_dir.iterdir() if p.is_dir() and not p.name.startswith(".")),
        key=lambda p: p.name,
    )
    if not candidates:
        return None
    return _snapshot_from_path(candidates[-1])


def find_snapshot(store: SnapshotStore, target: str) -> Optional[Snapshot]:
    """Resolve an operator-typed target: a sticky kind or a nightly id."""
    if target in (KIND_FIRST_KNOWN_GOOD, KIND_LAST_KNOWN_GOOD):
        return get_sticky(store, target)
    candidate = store.nightly_dir / target
    if not candidate.is_dir():
        return None
    return _snapshot_from_path(candidate)


def get_sticky(store: SnapshotStore, kind: str) -> Optional[Snapshot]:
    """Return the first- or last-known-good snapshot, or None if missing."""
    if kind == KIND_FIRST_KNOWN_GOOD:
        path = store.first_known_good_dir
    elif kind == KIND_LAST_KNOWN_GOOD:
        path = store.last_known_good_dir
    else:
        raise RollbackError(
            f"get_sticky kind must be {KIND_FIRST_KNOWN_GOOD} or "
            f"{KIND_LAST_KNOWN_GOOD}. Got {kind!r}."
        )
    if not path.is_dir():
        return None
    return _snapshot_from_path(path)


def _run_tar_create(
    source: Path,
    archive: Path,
    *,
    excludes: tuple[str, ...],
    exclude_patterns: tuple[str, ...] = (),
) -> None:
    """Create `archive` as a gzipped tar of `source`'s contents.

    The archive stores `source` under its top-level basename so extraction
    recreates the original directory structure. `excludes` are top-level
    entries; `exclude_patterns` are passed to tar as-is.
    """
    parent = source.parent
    basename = source.name
    cmd = ["tar", "-czf", str(archive)]
    for ex in excludes:
        cmd.extend(["--exclude", f"{basename}/{ex}"])
    for pattern in exclude_patterns:
        cmd.extend(["--exclude", pattern])
    cmd.extend(["-C", str(parent), basename])

    _LOG.info("snapshot: %s", " ".join(cmd))
    started = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
            env=clean_subprocess_env(),
            timeout=_TAR_TIMEOUT_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise RollbackError(
            f"tar timed out after {_TAR_TIMEOUT_SECONDS}s while archiving {source}"
        ) from exc
    except OSError as exc:
        raise RollbackError(f"could not invoke tar: {exc}") from exc

    elapsed_ms = int((time.monotonic() - started) * 1000)
    if proc.returncode != 0:
        raise RollbackError(
            f"tar failed (exit {proc.returncode}, after {elapsed_ms} ms): "
            f"{(proc.stderr or proc.stdout).strip()[:500]}"
        )
    _LOG.info(
        "snapshot: tar wrote %s in %d ms (%d bytes)",
        archive.name,
        elapsed_ms,
        archive.stat().st_size,
    )


def _run_tar_extract(archive: Path, *, into: Path, strip_to: str) -> None:
    """Extract `archive` into directory `into`.

    The archive is expected to contain a single top-level directory; the
    caller has already created the destination so extraction overlays its
    contents into the prepared `into / strip_to`. We use tar -C and trust
    the embedded paths because we wrote them ourselves.
    """
    cmd = ["tar", "-xzf", str(archive), "-C", str(into)]
    _LOG.info("restore: %s", " ".join(cmd))
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
            env=clean_subprocess_env(),
            timeout=_TAR_TIMEOUT_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise RollbackError(
            f"tar timed out after {_TAR_TIMEOUT_SECONDS}s while extracting {archive}"
        ) from exc
    except OSError as exc:
        raise RollbackError(f"could not invoke tar: {exc}") from exc

    if proc.returncode != 0:
        raise RollbackError(
            f"tar extract failed (exit {proc.returncode}): "
            f"{(proc.stderr or proc.stdout).strip()[:500]}"
        )

    final = into / strip_to
    if not final.is_dir():
        raise RollbackError(
            f"tar extract completed but {final} does not exist. "
            f"Archive may have been written with the wrong top-level name."
        )


def _sqlite_files(store: SnapshotStore) -> list[Path]:
    """The live SQLite databases a store wants copied safely, relative paths."""
    found: list[Path] = []
    for pattern in store.sqlite_globs:
        for path in sorted(store.source.glob(pattern)):
            if path.is_file():
                found.append(path.relative_to(store.source))
    return found


def _sqlite_tar_excludes(store: SnapshotStore, captured: list[str]) -> tuple[str, ...]:
    """tar patterns that keep the safely copied databases and sidecars out.

    Only databases that WERE copied are excluded; a `.db` file SQLite could
    not open as a database (some other format wearing the suffix) stays in
    the tar like any other file.
    """
    patterns: list[str] = []
    basename = store.source.name
    for rel in captured:
        patterns.append(f"{basename}/{rel}")
        for suffix in SQLITE_SIDECAR_SUFFIXES:
            patterns.append(f"{basename}/{rel}{suffix}")
    return tuple(patterns)


def _snapshot_sqlite(store: SnapshotStore, destination: Path) -> list[str]:
    """Copy each declared database with SQLite's online backup API, gzipped.

    The backup API reads a consistent image even while the owning daemon
    writes (it retries page batches on SQLITE_BUSY), which a tar of the
    main file plus a separate WAL file does not guarantee. Returns the
    relative paths captured. A database that cannot be read fails the
    snapshot: a rollback point without the state database is not one.
    """
    captured: list[str] = []
    for rel in _sqlite_files(store):
        live = store.source / rel
        out = destination / f"{rel}.gz"
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp_copy = out.with_suffix(".tmp")
        started = time.monotonic()
        try:
            src = sqlite3.connect(f"file:{live}?mode=ro", uri=True, timeout=30)
            try:
                dst = sqlite3.connect(str(tmp_copy))
                try:
                    src.backup(dst, pages=4096, sleep=0.05)
                finally:
                    dst.close()
            finally:
                src.close()
            with open(tmp_copy, "rb") as raw, gzip.open(out, "wb", compresslevel=6) as packed:
                shutil.copyfileobj(raw, packed, length=1024 * 1024)
        except sqlite3.DatabaseError as exc:
            if "not a database" in str(exc).lower():
                _LOG.warning(
                    "snapshot: %s is not a SQLite database (%s); archiving it as a plain file",
                    rel, exc,
                )
                out.unlink(missing_ok=True)
                continue
            raise RollbackError(f"could not snapshot SQLite database {rel}: {exc}") from exc
        except (sqlite3.Error, OSError) as exc:
            raise RollbackError(f"could not snapshot SQLite database {rel}: {exc}") from exc
        finally:
            tmp_copy.unlink(missing_ok=True)
        _LOG.info(
            "snapshot: sqlite backup of %s in %d ms (%d bytes gzipped)",
            rel, int((time.monotonic() - started) * 1000), out.stat().st_size,
        )
        captured.append(str(rel))
    return captured


def _restore_sqlite(snapshot: Snapshot, target: Path) -> None:
    """Put the snapshot's database copies back and drop stale sidecars."""
    sqlite_dir = snapshot.path / SQLITE_DIRNAME
    if not sqlite_dir.is_dir():
        return
    for packed in sorted(sqlite_dir.rglob("*.gz")):
        rel = packed.relative_to(sqlite_dir).with_suffix("")
        dest = target / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            with gzip.open(packed, "rb") as raw, open(dest, "wb") as out:
                shutil.copyfileobj(raw, out, length=1024 * 1024)
        except OSError as exc:
            raise RollbackError(f"could not restore SQLite database {rel}: {exc}") from exc
        for suffix in SQLITE_SIDECAR_SUFFIXES:
            Path(f"{dest}{suffix}").unlink(missing_ok=True)
        _LOG.info("restore: SQLite database %s put back", rel)


def _carry_over_excluded(backup: Path, target: Path, excludes: tuple[str, ...]) -> None:
    """Move the never-archived top-level entries from the pre-restore copy.

    An excluded entry that the archive somehow also contains (an older
    archive written with a shorter exclude list) is left as extracted.
    """
    for name in excludes:
        src = backup / name
        dst = target / name
        if not src.exists() or dst.exists():
            continue
        src.rename(dst)
        _LOG.info("restore: kept %s in place (excluded from archives)", dst)


def _has_meaningful_content(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        return any(path.iterdir())
    except OSError:
        return False


def _destination_for(store: SnapshotStore, kind: str, snapshot_id: str) -> Path:
    if kind == KIND_NIGHTLY:
        return store.nightly_dir / snapshot_id
    if kind == KIND_FIRST_KNOWN_GOOD:
        return store.first_known_good_dir
    return store.last_known_good_dir


def _swap_into_place(tmp_dir: Path, destination: Path) -> None:
    """Move `tmp_dir` to `destination`, replacing any existing directory."""
    if destination.exists():
        retired = destination.with_name(
            f".{destination.name}.replaced-{_generate_snapshot_id()}"
        )
        destination.rename(retired)
        try:
            tmp_dir.rename(destination)
        except Exception:
            retired.rename(destination)
            raise
        shutil.rmtree(retired, ignore_errors=True)
    else:
        tmp_dir.rename(destination)


def _snapshot_from_path(path: Path) -> Snapshot:
    meta_path = path / METADATA_FILENAME
    if not meta_path.exists():
        raise RollbackError(f"Snapshot at {path} is missing {METADATA_FILENAME}.")
    try:
        data = json.loads(meta_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RollbackError(
            f"Could not read snapshot metadata at {meta_path}: {exc}"
        ) from exc
    extra = data.get("extra")
    return Snapshot(
        path=path,
        snapshot_id=data.get("snapshot_id", path.name),
        kind=data.get("kind", "unknown"),
        captured_at=data.get("captured_at", ""),
        version=data.get("version") or data.get("openclaw_version"),
        source=data.get("source") or data.get("openclaw_config_source", ""),
        verified_healthy=bool(data.get("verified_healthy", False)),
        extra=extra if isinstance(extra, dict) else {},
    )


def _generate_snapshot_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
